# version of docker-compose
version: "3.9"
# 'services' are equivalent to 'containers'
services:
  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"

  server:
    build: ./server
    ports:
      - "5000:5000"

  client:
    build: ./client
    ports:
      - "3000:3000"
